name: Generate Wordpacks List

on:
  push:
    branches:
      - main
    paths:
      - 'static/wordpacks/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate list of wordpacks
        run: |
          find static/wordpacks -type f > static/wordpacks.txt
